"""Generate the documents that must never be written by hand, or check they are current.

- docs/data-model.md            from the project models and their contracts
- docs/api/errors.md            from the registered error codes
- docs/features/domain-events.md from event classes, handlers, and emit() calls
- docs/api/openapi.json         from drf-spectacular, when it is installed

`python deploy/generate_docs.py` writes them; `--check` fails when a committed
copy is stale.
"""

from __future__ import annotations

import ast
import dataclasses
import importlib
import inspect
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from deploy._django import setup  # noqa: E402 - the path is set just above


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def render_data_model() -> str:
    from django.apps import apps

    from config import architecture

    lines = [
        "# Data model",
        "",
        "Generated by `deploy/generate_docs.py`. Do not edit.",
        "",
    ]
    for app_label in architecture.PROJECT_APPS:
        models = sorted(
            apps.get_app_config(app_label).get_models(), key=lambda m: m.__name__
        )
        for model in models:
            meta = model._meta
            lines += [
                f"## `{meta.label}`",
                "",
                inspect.cleandoc(model.__doc__ or ""),
                "",
            ]
            lines += [
                "| Field | Type | Null | Default | Help |",
                "|---|---|---|---|---|",
            ]
            for field in [*meta.local_fields, *meta.local_many_to_many]:
                default = field.default if field.has_default() else ""
                if callable(default):
                    default = getattr(default, "__name__", "callable")
                lines.append(
                    f"| `{field.name}` | {type(field).__name__} | {field.null} | "
                    f"{_cell(default)} | {_cell(field.help_text)} |"
                )
            for constraint in meta.constraints:
                lines.append(
                    f"- Constraint `{constraint.name}` ({type(constraint).__name__})"
                )
            for index in meta.indexes:
                lines.append(f"- Index `{index.name}` on {', '.join(index.fields)}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_errors() -> str:
    from common.api_errors import BUILTIN_ERROR_CODES
    from common.errors import CATEGORY_STATUS, ERROR_CODES

    rows = {
        code: (str(t), status, message)
        for code, t, status, message in BUILTIN_ERROR_CODES
    }
    for code, cls in ERROR_CODES.items():
        rows[code] = (
            str(cls.category),
            CATEGORY_STATUS[cls.category],
            str(cls.default_message),
        )
    lines = [
        "# Error catalog",
        "",
        "Generated by `deploy/generate_docs.py`. Do not edit.",
        "",
        "| Code | Type | Status | Default message |",
        "|---|---|---|---|",
    ]
    lines += [
        f"| `{c}` | `{t}` | {s} | {_cell(m)} |" for c, (t, s, m) in sorted(rows.items())
    ]
    return "\n".join(lines) + "\n"


def _emit_sites(root: Path) -> dict[str, list[str]]:
    from config import architecture

    sites: dict[str, list[str]] = {}
    for app in architecture.PROJECT_APPS:
        for path in sorted((root / app).rglob("*.py")):
            if {"tests", "migrations"} & set(path.relative_to(root).parts):
                continue
            for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
                if not (
                    isinstance(node, ast.Call)
                    and node.args
                    and (
                        getattr(node.func, "id", None)
                        or getattr(node.func, "attr", None)
                    )
                    == "emit"
                ):
                    continue
                target = (
                    node.args[0].func
                    if isinstance(node.args[0], ast.Call)
                    else node.args[0]
                )
                if isinstance(target, ast.Attribute) and isinstance(
                    target.value, ast.Name | ast.Attribute
                ):
                    target = target.value
                name = getattr(target, "id", None) or getattr(target, "attr", None)
                sites.setdefault(str(name), []).append(
                    f"{path.relative_to(root)}:{node.lineno}"
                )
    return sites


def render_events(root: Path) -> str:
    from config import architecture
    from events.domain import event_classes
    from events.services.registry import registry

    for app in architecture.PROJECT_APPS:
        try:
            importlib.import_module(f"{app}.events")
        except ModuleNotFoundError as error:
            if error.name != f"{app}.events":
                raise
    sites = _emit_sites(root)
    lines = [
        "# Domain events",
        "",
        "Generated by `deploy/generate_docs.py`. Do not edit.",
        "",
    ]
    for name, cls in sorted(event_classes().items()):
        fields = ", ".join(f"`{f.name}`" for f in dataclasses.fields(cls))
        lines += [
            f"## `{name}` (v{cls.version})",
            "",
            f"- Class: `{cls.__module__}.{cls.__qualname__}`",
            f"- Fields: {fields}",
            f"- Emitted by: {', '.join(f'`{s}`' for s in sites.get(cls.__name__, [])) or 'nowhere'}",
            "- Handlers:",
        ]
        handlers = [h for h in registry.all() if h.event_name == name]
        lines += [
            f"  - `{h.key}` ({h.mode}, queue `{h.queue}`)"
            for h in sorted(handlers, key=lambda h: h.key)
        ]
        if not handlers:
            lines.append("  - none")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def render_openapi() -> str | None:
    try:
        from drf_spectacular.generators import SchemaGenerator
        from drf_spectacular.renderers import OpenApiJsonRenderer
    except ImportError:
        return None
    schema = SchemaGenerator().get_schema(request=None, public=True)
    rendered: bytes = OpenApiJsonRenderer().render(schema, renderer_context={})
    return rendered.decode() + "\n"


def main(argv: list[str]) -> int:
    root = setup()
    documents = {
        "docs/data-model.md": render_data_model(),
        "docs/api/errors.md": render_errors(),
        "docs/features/domain-events.md": render_events(root),
    }
    openapi = render_openapi()
    if openapi is not None:
        documents["docs/api/openapi.json"] = openapi
    if "--check" in argv:
        stale = [
            p
            for p, text in documents.items()
            if not (root / p).exists() or (root / p).read_text(encoding="utf-8") != text
        ]
        for path in stale:
            print(f"stale: {path} (run python deploy/generate_docs.py)")
        return 1 if stale else 0
    for path, text in documents.items():
        (root / path).parent.mkdir(parents=True, exist_ok=True)
        (root / path).write_text(text, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
