# Generated by Django 6.0.8 on 2026-09-28 06:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OutboxEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(
                        blank=True, help_text="Tenant of the event, if any.", null=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.PositiveSmallIntegerField()),
                ("subject_id", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
            ],
            options={
                "verbose_name": "outbox event",
                "verbose_name_plural": "outbox events",
                "indexes": [
                    models.Index(
                        fields=["name", "created_at"], name="evt_name_created_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventDelivery",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "handler",
                    models.CharField(
                        help_text="Registered handler key: <module>.<function>.",
                        max_length=200,
                    ),
                ),
                ("queue", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("dead", "Dead"),
                            ("reconciliation_required", "Reconciliation required"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "attempt_count",
                    models.PositiveIntegerField(default=0, help_text="Fencing token."),
                ),
                ("lease_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_attempt_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("dead_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="events.outboxevent",
                    ),
                ),
            ],
            options={
                "verbose_name": "event delivery",
                "verbose_name_plural": "event deliveries",
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"], name="evd_status_next_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("event", "handler"),
                        name="events_eventdelivery_event_handler_uniq",
                    )
                ],
            },
        ),
    ]
